### ISSUE TITLE
Why not libseccomp?

### ISSUE THREAD

**Issue by oxr463** [giuseppe/easyseccomp#1]
I love seeing new seccomp projects!

What is the use-case here? Since this uses libseccomp internally, it must meet some requirement(s) that the library doesn't fulfill.

It would be good to explain this in the README.md file.

**Comment by giuseppe** [comment]
I've tried to explain some of the reasons here: https://www.scrivano.org/posts/2021-01-30-easyseccomp/

Do you think that information must be moved to the `README.md` file?

**Comment by oxr463** [comment]
> I've tried to explain some of the reasons here: https://www.scrivano.org/posts/2021-01-30-easyseccomp/
> 
> Do you think that information must be moved to the `README.md` file?

That is an excellent article. Maybe we could just link to it from the README.md file?

**Comment by giuseppe** [comment]
> That is an excellent article. Maybe we could just link to it from the README.md file?

sure, I've added a link.  Just let me know if there is anything more you'd like to see added there.
