### ISSUE TITLE
Non-obvious build failure when lex not installed

### ISSUE THREAD

**Issue by tsavola** [giuseppe/easyseccomp#5]
configure succeeds even when there is no lex installed. However, it does mention it:

```
...
checking for flex... no
checking for lex... no
...
```

After the successful configure, make fails like this:

```
  CC       src/main.o
  LEX      src/libeasyseccomp_a-lexer.c
  CC       src/libeasyseccomp_a-libeasyseccomp_a-lexer.o
gcc: error: ./src/libeasyseccomp_a-lexer.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
make: *** [Makefile:765: src/libeasyseccomp_a-libeasyseccomp_a-lexer.o] Error 1
```

It took some figuring out to learn that I had to install flex. (I'm using Ubuntu 20.04.)

**Comment by giuseppe** [comment]
thanks for opening the issue.

Indeed it is annoying, I've pushed a commit to check for lex an yacc presence, otherwise fail
